name: pbdl
description: A starting point for Dart libraries or applications.
version: 2.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.1.0'

dependencies:
  json_annotation: ^4.8.1
  hex: ^0.2.0
  quick_log: ^5.3.0
  http2: ^2.0.1
  path: ^1.8.3
  azblob: ^2.3.0
  recase: ^4.1.0
  archive: ^3.4.9
  meta: ^1.11.0
  uuid: ^4.2.2
  get_it: ^7.6.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  pedantic: ^1.11.1
  test: ^1.24.3
